### ISSUE TITLE
Breaking: Add proper package names

### ISSUE THREAD

**Issue by derTobsch** [focus-shift/jollyday#298]
### More information

The package names are atm not very handy:

* jollyday-core is `de.focus-shift.<packages>`
* jollyday-jaxb is `de.focus-shift.jaxb.<packages>`
* jollyday-tests is `de.focus-shift.<packages>`

This will be changed to:

* jollyday-core is `de.focus-shift.jollyday.core.<packages>`
  * contains the API used by the developers
  * contains the core jollyday java code and logic 
  * contains all XML holiday files 
* jollyday-jaxb is `de.focus-shift.jollyday.jaxb.<packages>`
  * requires `jollyday.core`
* jollyday-tests is `de.focus-shift.jollyday.tests.<packages>`  
  * requires `jollyday.core`
  * requires `jollyday.jaxb`
 

- [x] adapt readme and examples

see https://github.com/focus-shift/jollyday/issues/300#issuecomment-1716271998

**Comment by derTobsch** [comment]
> Is there any plan, when release 1.0.0 will happen already?
> 
> Also: Does this project follow [Semantic Versioning](https://semver.org/)? If so, this change could already be done [without](https://semver.org/#spec-item-4) a major version number increment. A discussion on when to bump to 1.0.0 or whether it already should not be 0.y.z anymore, should be had nevertheless, of course.
> 
> > ```
> > * [ ]  provide an open rewrite recipe https://docs.openrewrite.org/
> > 
> > * [ ]  provide an search and replace string
> > ```
> 
> Is this intended for the users or for internal purposes only to make this change? For internal purposes the refactoring possibilities of an IDE like IntellIJ should be enough in my opinion, I haven't tried it yet, though. I did a similar refactoring with just an IDE a while back however, and it worked really well.

This will be a breaking change and we use semantic versioning so we can only do that with the 1.0.0. This will cause all developers to fix their imports.

**Comment by derTobsch** [comment]
> > ```
> > * jollyday-holidays is `de.focus-shift.jollyday.holidays.<packages>`
> >   
> >   * contains all XML holiday files
> >   * the module needs to be `open`
> > ```
> 
> Why does it need to be an open module? Why don't (qualified) `opens` statements suffice?

I need to dig deeper into it, but this is because the `Holidays_<country>.xml` files are placed in `.../resources/holidays/` and the classloader cannot load it until it is open. Maybe it is possible to just open a specific module. This is the reason, if we need to completely open it up, that the `Holidays_<country>.xml` files should be placed in an own module.

**Comment by derTobsch** [comment]
> @derTobsch How would the Jackson support fit in there? I suppose that would be it's own module similar to jollyday-jaxb?
> 
> As our project only uses Jackson2, it breaks for me, when I replace `jollyday-jaxb` with `jollyday-core` in my pom.xml, as it then only pulls in `org.threeten:threeten-extra` and `org.slf4j:slf4j-api` (that would otherwise be pulled in by a different dependency), but not `jakarta.xml.bind:jakarta.xml.bind-api` (that then get's pulled in by a different dependency) nor `org.glassfish.jaxb:jaxb-runtime`, despite only using classes from jollyday.core and only requiring `jollyday.core` in my `module-info.java`. It then fails to load the application context with the following error:
> 
> ```java
> Caused by: java.lang.ClassNotFoundException: de.focus_shift.jaxb.JaxbConfigurationService
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> [...]
> 	at jollyday.core@0.20.0-SNAPSHOT/de.focus_shift.datasource.ConfigurationServiceManager.instantiateDataSource(ConfigurationServiceManager.java:25)
> 	... 142 more
> ```
> 
> respectively
> 
> ```java
> Caused by: java.lang.ClassNotFoundException: de.focus_shift.jaxb.JaxbConfigurationService
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> [...]
> 	at jollyday.core@0.19.1/de.focus_shift.datasource.ConfigurationServiceManager.instantiateDataSource(ConfigurationServiceManager.java:25)
> 	... 142 more
> ```

It is not possible to run jollyday without the `jollyday-jaxb` dependency, because there is not only the jaxb dependency in there but also the mappings e.g.

**Comment by derTobsch** [comment]
> > I need to dig deeper into it, but this is because the `Holidays_<country>.xml` files are placed in `.../resources/holidays/` and the classloader cannot load it until it is open. Maybe it is possible to just open a specific module. This is the reason, if we need to completely open it up, that the `Holidays_<country>.xml` files should be placed in an own module.
> 
> I am not sure, that this is related, but why is there this custom `ClassLoadingUtil` and `getResource` anyway? From just briefly looking at the code, it seems overly complicated to right custom functions, that effectively do the same as the JDK provided methods do. Sure, your `getResource` can return `null`, whereas the JDK throws an `NullPointerException`, but can't you just handle this exception at the caller instead of handling `null` at the caller, where you also just throw an exception from what I can see? Without having tried it further, I would suspect that the issues could arise, when the custom `ClassLoadingUtil`/`ResourceUtil` gets called from a different module and then one tries to load code/resources from one's own module via the indirection of this custom class from a different module.

There is a lot of code that I did not write and I am going into it step by step to understand why this code is there and maybe is not needed any more with a baseline of java 11. So This steps will be done later while the library will evolve.

**Comment by derTobsch** [comment]
I will take this issue for a smaller scope to rename the packages and put it into the milestone 0.20.0
