### ISSUE TITLE
Add java module info

### ISSUE THREAD

**Issue by derTobsch** [focus-shift/jollyday#300]
### More information

In order for this library to be usable in a modular Java application that is distributed with a jlink image, it needs to be made modular.

see https://github.com/jqwik-team/jqwik/tree/main/test-modular-api for some integration tests

**Comment by derTobsch** [comment]
You could test against #299, that would be nice to know if this does work.

**Comment by derTobsch** [comment]
Is your project open source? Or could you provide an example projects? That would help to save some time on my side :)

**Comment by derTobsch** [comment]
> Is your project open source? Or could you provide an example projects? That would help to save some time on my side :)

Ok, i just started one :)

**Comment by derTobsch** [comment]
@XSpielinbox why do you need so many packages from jollyday? Can you add some code snippets to see how you receive the holiday information?

**Comment by derTobsch** [comment]
> > You could test against #299, that would be nice to know if this does work.
> 
> Yes, I want to do that. However, I have to figure out how to do a release myself from my local copy of that branch and build the Spring Boot project with that own release.
> 
> If you have any guidance / know helpful resources on that, that would really help.

Check out this project and run `mvn clean install` after that the version is available in your local repository and you can use it locally.

**Comment by derTobsch** [comment]
@XSpielinbox do you know what i have to open up?

```
org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessException-->module de.focus_shift.jollyday.with.modules.app does not open de.focus_shift.jollyday to unnamed module @778d1062
```

spring.core or spring.context or what is it?

**Comment by derTobsch** [comment]
> > @XSpielinbox why do you need so many packages from jollyday? Can you add some code snippets to see how you receive the holiday information?
> 
> We have to classes using jollyday: The first class has the following snippet in it's constructor:
> 
> ```java
> Set<String> supportedSet = HolidayManager.getSupportedCalendarCodes();
> for (String code : supportedSet) {
>     CalendarHierarchy hierarchy = HolidayManager.getInstance(ManagerParameters.create(code))
>             .getCalendarHierarchy();
>     recursiveHolidays(hierarchy, null, null);
> }
> ```
> 
> It also defines two additional methods, that use it:
> 
> ```java
> private void recursiveHolidays(CalendarHierarchy hierarchy, String prevCode, String prevDesc) {
>     [...]
>     for (Map.Entry<String, CalendarHierarchy> child : hierarchy.getChildren().entrySet()) {
>         if (prevCode == null) {
>             recursiveHolidays(child.getValue(), id, desc);
>         } else {
>             recursiveHolidays(child.getValue(), prevCode + "_" + id, prevDesc + " - " + desc);
>         }
>     }
> }
> ```
> 
> and
> 
> ```java
> private boolean testHolidays(String[] countries, LocalDate date) {
>     for (String holidayCode : countries) {
>         String[] args = holidayCode.split("_");
>         String[] adjArgs = Arrays.copyOfRange(args, 1, args.length);
>         HolidayManager manager = HolidayManager.getInstance(ManagerParameters.create(args[0]));
>         if (manager.isHoliday(date, adjArgs)) {
>             return true;
>         }
>     }
>     return false;
> }
> ```
> 
> So in total it uses the classes `CalendarHierarchy`, `HolidayManager` and `ManagerParameters`.
> 
> The second class defines the following method using jollyday:
> 
> ```java
> public CalendarView view(boolean termsOnly) {
>     [...]
>     for (String holidayCode : holidaySet) {
>         String[] args = holidayCode.split("_");
>         String[] adjArgs = Arrays.copyOfRange(args, 1, args.length);
>         HolidayManager manager = HolidayManager.getInstance(ManagerParameters.create(args[0]));
>         Set<Holiday> holidaySet = manager.getHolidays(startDate, endDate, adjArgs);
>         holidaySet.forEach(holiday -> {
>             List<CalendarItem> existingList = calendar.getOrDefault(holiday.getDate(), new LinkedList<>());
>             existingList.add(new CalendarItem(holiday.getDescription(), holidayCode));
>             calendar.put(holiday.getDate(), existingList);
>         });
>     }
>     return new CalendarView(calendar, this.holidaySet);
> }
> ```
> 
> So in total it uses the classes `Holiday`, `HolidayManager` and `ManagerParameters`.
> 
> I hope this helps. Do you have suggestions, how this could be done better?

Yes that helps a lot. I think you should be able to build your application with the pr #299 or?

**Comment by derTobsch** [comment]
> > @XSpielinbox do you know what i have to open up?
> > ```
> > org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessException-->module de.focus_shift.jollyday.with.modules.app does not open de.focus_shift.jollyday to unnamed module @778d1062
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > spring.core or spring.context or what is it?
> 
> You definitely need to open reflection to `spring.core`; so you have to add
> 
> ```java
> opens [your.spring.application.package] to spring.core;
> ```
> 
> to your `module-info.java` for every package that causes this kind of issues. There might be a package, that depends on some class that is part of a jar, that isn't a module, therefore is included on the classpath, therefore being part of the unnamed module, where you then need to add:
> 
> ```java
> opens [your.spring.application.package];
> ```
> 
> Note: when you add this line, you don't need another `opens` statement for this package, as this is an unqualified `opens`.

I already did that, but it does not work until I add `--add-reads de.focus_shift.jollyday=ALL-UNNAMED` as jvm param. I have no idea why i need to define both.

Thanks for your response!

**Comment by derTobsch** [comment]
> 

I got a working example project and this is my `module.info.java`

```java
module de.focus_shift.jollyday {

    opens de.focus_shift.jollyday;

    requires jollyday.core;

    requires spring.web;
    requires spring.context;
    requires spring.boot;
    requires spring.boot.autoconfigure;
}
```

Did you requre jollyday.jaxb? You only need to require the core package. I think It would be nice for a 1.0.0 version to split the packages/modules into:
* jollyday.api
* jollyday.core
* jollyday.holidays (to open up reflection for the classloader)
* jollyday.jaxb
* jollyday.jackson

So that only the `jollyday.api` should be used from the applications.

**Comment by derTobsch** [comment]
> Interestingly though, when only requiring the `jollyday.core` module while using version 0.19.1, my IDE shows errors `Package 'de.focus_shift' is declared in module 'jollyday.jaxb', but module '[my.application.module]' does not read it`, but everything works fine, nevertheless (as I can verify in the jollyday source code too, that all used classes are in `jollyday.core`). When using the 0.20.0-SNAPSHOT from branch java-modules (commit [735f3da](https://github.com/focus-shift/jollyday/commit/735f3dabc31eb59c9a574d082537c9fb6dfaef8f)), it does not show the errors (and everything works fine too). So it seems to me like it is confused, if the imported dependency is different than the automatic module, it contains.

I will update the readme to clear, which dependencies and which modules are required. That will make thinks clearer.

**Comment by derTobsch** [comment]
> > > 
> > 
> > 
> > I got a working example project and this is my `module.info.java`
> > ```java
> > module de.focus_shift.jollyday {
> > 
> >     opens de.focus_shift.jollyday;
> > 
> >     requires jollyday.core;
> > 
> >     requires spring.web;
> >     requires spring.context;
> >     requires spring.boot;
> >     requires spring.boot.autoconfigure;
> > }
> > ```
> 
> Thank you! Having the module name very similar to the one of it's dependencies or the dependencies package names is very confusing though and might cause additional issues.
> 
> I guess my example project is not needed then any more.
> 
> > Did you requre jollyday.jaxb? You only need to require the core module. [...]
> 
> Indeed! As the installation steps, said one should use `jollyday-jaxb` as a dependency, I thought, that this would be the minimum, one would have to require. When removing the `requires jollyday.jaxb;` statement, it solves the split packages error in 0.19.1, which then runs absolutely fine, but with the java-modules branch (commit [f9b3b60](https://github.com/focus-shift/jollyday/commit/f9b3b60b3f3c7d9b4f970bdc9ce1a6f0b8b8f9cb)) it still fails to load the application context:
> 
> ```java
> Caused by: java.lang.IllegalStateException: Cannot instantiate configuration from URL 'null'.
> 	at de.focus_shift.jaxb.JaxbConfigurationService.getConfiguration(JaxbConfigurationService.java:21)
> 	at jollyday.core@0.20.0-SNAPSHOT/de.focus_shift.impl.DefaultHolidayManager.doInit(DefaultHolidayManager.java:200)
> [...]
> 	... 127 more
> Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.openStream()" because "resourceUrl" is null
> 	at de.focus_shift.jaxb.JaxbConfigurationService.getConfiguration(JaxbConfigurationService.java:18)
> 	... 143 more
> ```
> 
> However, it does then seem like a giant hack, to only make use of `jollyday.core`, but adding `jollyday-jaxb` as a dependency. What is the current difference between the two? What is needed for what? What classes should normally be used when building functionality using Jollyday?
> 
> > [...] I think It would be nice for a 1.0.0 version to split the packages/modules into:
> > ```
> > * jollyday.api
> > 
> > * jollyday.core
> > 
> > * jollyday.holidays (to open up reflection for the classloader)
> > 
> > * jollyday.jaxb
> > 
> > * jollyday.jackson
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So that only the `jollyday.api` should be used from the applications. see #298
> 
> sounds like a plan. : ) What do you mean with "to open up reflection for the classloader"?
> 
> > I just updated the branch on #299. Please test it with this informations in your application :)
> 
> You just made Jollyday core an open module, if I see that correctly, thereby allowing reflection for everyone. I will definitely test, whether this solves the problem, but I don't see any reason, why a library / Jollyday in particular should do that. It to a certain degree removes all the security benefits, the Java Module system brings. I also don't know of any other library that does that.

I dig deeper into the code and found the pieces that uses reflection and only allowed reflection in this packages. Please check out the branch with the commit a3fd4ac and verify if it is working. My examples do work. After that I would merge this branch.

I also added some information to the readme about the dependencies and module info

**Comment by derTobsch** [comment]
> Also: Why did you include `requires java.xml;` in the `module-info.java` from `jollyday-jaxb`? From what I can see it is used nowhere and when I remove it it works fine for me too.

This is because the tests in the core module needs `java.xml`.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project jollyday-core: Compilation failure
[ERROR] /home/schneider/projects/focus-shift/jollyday/jollyday-core/src/test/java/de/focus_shift/XMLValidationTest.java:[8,27] package javax.xml.transform.stream is not visible
[ERROR]   (package javax.xml.transform.stream is declared in module java.xml, but module jollyday.core does not read it)
```

I am looking into this atm. Maybe I can replace it with something different. But to disable the modulePath in test via surefire seems not ok.

**Comment by derTobsch** [comment]
> > I dig deeper into the code and found the pieces that uses reflection and only allowed reflection in this packages. Please check out the branch with the commit [a3fd4ac](https://github.com/focus-shift/jollyday/commit/a3fd4accabd290e491ae789be1145fda5b2594da) and verify if it is working. My examples do work. After that I would merge this branch.
> 
> So: I did some testing with our application and yes, it works with commit [a3fd4ac](https://github.com/focus-shift/jollyday/commit/a3fd4accabd290e491ae789be1145fda5b2594da), but at least for our application opening `descriptions` and `de.focus_shift.datasource` does not seem necessary at all. Why did you add them?
>

Without descriptions there will be no translations.
Without datasource the ConfigurationService will not be instantiated, because this is done via reflection atm.

> > I also added some information to the readme about the dependencies and module info
> 
> Thank you. It now reads to me, that one shall add both `jollyday-core` and `jollyday-jaxb` as a dependency, is that correct? It also works with only `jollyday-jaxb` as before, but when adding `jollyday-core` the highlighting errors in the IDE disappear.

You need both. Jaxb has a transitive dependency on the core dependency. So it would run, but it is common sense to use a dependency directly if you use it directly. So it is better and I would say recommanded to add the core and jaxb.
